Fix: /home/travis/build/phstc/influxdb-cli/spec/spec_helper.rb:10:in `block in <top (required)>': undefined method `color_enabled=' for #<RSpec::Core::Configuration:0x00000002af5940> (NoMethodError)